kumuluzee:
  name: picture
  env:
    name: dev
  version: 1.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
  - jndi-name: picture
    connection-url: jdbc:postgresql://192.168.99.100:5434/picture
    username: postgres
    password: admin
    max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
app-properties:
  external-services:
    enabled: true