apiVersion: apps/v1
kind: Deployment
metadata:
  name: picture-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picture
  template:
    metadata:
      labels:
        app: picture
    spec:
      containers:
      - image: rsovaje/picture:0.3
        name: picture
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: gcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_SERVER_BASEURL
          value: http://159.122.177.26:8082
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-pass
              key: KUMULUZEE_DATASOURCES0_PASSWORD
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://sl-eu-gb-p00.dblayer.com:16880/compose
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          value: admin
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: picture
spec:
  type: NodePort
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: picture